[package]
name = "kvs"
version = "0.1.0"
authors = ["lwshang <lwsh37@gmail.com>"]
description = "A key-value store"
edition = "2018"

[dependencies]
clap = "2.33.0"

[dev-dependencies]
assert_cmd = "0.11.1"
predicates = "1.0.1"